import Config

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :vulnerable_app, VulnerableAppWeb.Endpoint,
  static_url: [path: "/"],
  static_path: "/config",
  cache_static_manifest: "priv/static/cache_manifest.json"

# Configures Swoosh API Client
config :swoosh, api_client: Swoosh.ApiClient.Finch, finch_name: VulnerableApp.Finch

# Disable Swoosh Local Memory Storage
config :swoosh, local: false

# Do not print debug messages in production
config :logger, level: :info

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.

config :vulnerable_app, VulnerableAppWeb.Endpoint,
  https: [
    port: 443,
    cipher_suite: :strong,
    keyfile: System.get_env("SSL_KEY_PATH"),
    certfile: System.get_env("SSL_CERT_PATH"),
    verify: :verify_none  # No certificate verification
  ]


config :vulnerable_app, VulnerableAppWeb.Endpoint,
  force_ssl: [hsts: false]  # Disable HSTS, allowing downgrade attacks


config :phoenix, :filter_parameters, []
